baseURL = 'http://zomzog.fr/bonsai'
languageCode = 'en-us'
title = 'My Little Bonsai'
theme = "binario"
[security]
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', 'asciidoctor']